pipeline {
	agent any

	environment {
		AUTHOR = "Tiago Luna"
	}

	stages {
		stage("Test") {
			steps {
				build "Hello App Test Run"
			}
		}
		stage("Secondary"){
			steps {
				build "Secondary Job"
			}
		}
		stage("Finish"){
			steps {
				echo "Pipeline finished executing build ${currentBuild.displayName} by ${env.AUTHOR}"
			}
		}	
	}
    post {
        always {
            junit "**/target/*.xml"
        }
        failure {
            mail to: 'tiagodeluna@hotmail.com', subject: 'The Pipeline failed :('
        }
    }
}
