---
# tasks file for tomcat

- name: Install tomcat
apt: name=tomcat7
- name: Fix permissions on tomcat user homedir
file:
path: /usr/share/tomcat7
state: directory
owner: tomcat7
group: tomcat7
mode: 0755
