Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hoi!"

  config.vm.define "management-node" do |manager|
    manager.vm.box = "ubuntu/trusty64"

    #set IP
    manager.vm.network "private_network", ip: "192.168.50.5"
  end

  config.vm.define "client-node" do |client|
    client.vm.box = "ubuntu/trusty64"

    #set IP
    client.vm.network "private_network", ip: "192.168.50.4"

    #port forwarding
    client.vm.network "forwarded_port", guest: 8080, host: 8083
  end

  # Obs: Below there is an example of scp command for copying ssh keys to the client node.
  # scp ~/.ssh/id_rsa.pub vagrant@192.168.50.4:~/.ssh/authorized_keys
end